server:
  port: 8080

spring:
    datasource:
        name: demodb
        url: jdbc:mysql://127.0.0.1:3306/demodb?useSSL=true
        username: root
        password: root
        # 使用druid数据源
        type: org.springframework.jdbc.datasource.DriverManagerDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/demo/mapper/UserMapper.xml
  type-aliases-package: com.demo.mapper

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql